ALTER TABLE "User" ADD COLUMN "phone" TEXT;

ALTER TABLE "Instance" ADD COLUMN "user_id" TEXT;

ALTER TABLE "Instance" ADD CONSTRAINT "Instance_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
